import type { AppSnapshot } from './models';

export const initialSnapshot: AppSnapshot = {
  tenant: {
    id: 'tenant-chauffeur-atelier',
    slug: 'chauffeur-atelier',
    branding: {
      brandName: 'Chauffeur Atelier',
      brandShortName: 'Atelier',
      brandMark: 'C',
      brandTagline: 'Vintage and exotic arrivals for life defining occasions',
      logoUrl: '',
      faviconUrl: '',
      contactEmail: 'concierge@chauffeuratelier.com',
      contactPhone: '+351 210 000 900',
      whatsapp: '+351 912 888 111',
      serviceArea: 'Lisbon, Cascais, Sintra and destination coverage across Portugal',
      conciergeHours: 'Daily, 08:00 to 22:00',
      supportDomain: 'chauffeuratelier.com',
      legalCompanyName: 'Chauffeur Atelier Experiences, Lda.',
      socialInstagram: 'https://instagram.com/chauffeuratelier',
      socialFacebook: 'https://facebook.com/chauffeuratelier',
    },
    theme: {
      templateId: 'classic-luxury',
      primaryColor: '#d4a457',
      secondaryColor: '#6f543a',
      accentColor: '#f1c27d',
      surfaceColor: '#171310',
      surfaceSoftColor: '#201b16',
      headingFont: "'Cormorant Garamond', serif",
      bodyFont: "'Manrope', sans-serif",
      radiusScale: 'rounded',
      density: 'comfortable',
    },
    content: {
      heroEyebrow: {
        en: "Vintage and exotic arrivals for life's defining occasions",
        pt: 'Chegadas vintage e exoticas para os momentos mais marcantes da vida',
      },
      heroTitle: {
        en: 'Arrival, photographed beautifully.',
        pt: 'Uma chegada feita para ser fotografada.',
      },
      heroSubtitle: {
        en: 'Book heritage icons and exotic statement cars for weddings, proposals, editorials, private transfers, and unforgettable events.',
        pt: 'Reserve iconicos classicos e viaturas exoticas para casamentos, pedidos de casamento, editoriais, transfers privados e eventos inesqueciveis.',
      },
      heroPrimaryCtaLabel: {
        en: 'Explore the fleet',
        pt: 'Explorar a frota',
      },
      heroSecondaryCtaLabel: {
        en: 'Request a tailored offer',
        pt: 'Pedir proposta personalizada',
      },
      availabilityPanelTitle: {
        en: 'Premium search in one step',
        pt: 'Pesquisa premium num so passo',
      },
      availabilityPanelHint: {
        en: 'Customers usually shortlist two to three cars before requesting a final offer. Starting prices begin at {{price}}.',
        pt: 'Os clientes costumam selecionar duas a tres viaturas antes de pedir a proposta final. Os precos comecam em {{price}}.',
      },
      trustSectionTitle: {
        en: 'Designed for emotional, high trust bookings',
        pt: 'Pensado para reservas emocionais e de elevada confianca',
      },
      trustSectionDescription: {
        en: 'This is event mobility, not commodity rental. The product emphasizes atmosphere, confidence, and a clear handoff into tailored concierge service.',
        pt: 'Isto nao e aluguer comum. O produto privilegia ambiente, confianca e uma transicao clara para um servico concierge personalizado.',
      },
      footerTagline: {
        en: 'Premium concierge bookings for weddings, proposals, editorials, and executive arrivals.',
        pt: 'Reservas premium com concierge para casamentos, pedidos de casamento, editoriais e chegadas executivas.',
      },
      footerColumns: [
        {
          id: 'service-area',
          heading: { en: 'Service areas', pt: 'Areas de servico' },
          body: {
            en: 'Lisbon, Cascais, Sintra and destination events across Portugal.',
            pt: 'Lisboa, Cascais, Sintra e eventos de destino em todo o pais.',
          },
        },
        {
          id: 'experience-promise',
          heading: { en: 'Experience promise', pt: 'Promessa de experiencia' },
          body: {
            en: 'Tailored offers, availability clarity, and white glove operations from inquiry to event day.',
            pt: 'Propostas personalizadas, clareza na disponibilidade e operacao white glove do primeiro contacto ao dia do evento.',
          },
        },
      ],
      homepageSections: [
        { key: 'featuredFleet', enabled: true },
        { key: 'valueProps', enabled: true },
        { key: 'process', enabled: true },
        { key: 'testimonials', enabled: true },
        { key: 'faqPreview', enabled: true },
      ],
      legalNotice: {
        en: 'Final availability and pricing are always confirmed by the concierge team before fulfillment.',
        pt: 'A disponibilidade e o preco final sao sempre confirmados pela equipa concierge antes da execucao.',
      },
      quoteAssistanceLabel: {
        en: 'Request concierge help',
        pt: 'Pedir ajuda ao concierge',
      },
    },
    navigation: [
      { id: 'fleet', path: '/fleet', translationKey: 'nav.fleet', visible: true },
      { id: 'favorites', path: '/favorites', translationKey: 'nav.favorites', visible: true },
      { id: 'compare', path: '/compare', translationKey: 'nav.compare', visible: true },
      { id: 'dashboard', path: '/customer/dashboard', translationKey: 'nav.dashboard', visible: true },
      { id: 'faq', path: '/faq', translationKey: 'nav.faq', visible: true },
      { id: 'contact', path: '/contact', translationKey: 'nav.contact', visible: true },
    ],
    seo: {
      siteTitle: 'Chauffeur Atelier | Vintage and Exotic Event Arrivals',
      siteDescription: 'Premium event car booking platform for weddings, proposals, photoshoots, transfers, and luxury arrivals.',
      keywords: ['vintage wedding car', 'luxury event transfer', 'exotic car booking', 'classic car proposal'],
      ogImageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1600&q=80',
      themeColor: '#d4a457',
    },
    localization: {
      defaultLocale: 'en',
      enabledLocales: ['en', 'pt', 'es', 'fr', 'de', 'it'],
      currency: 'EUR',
    },
    publication: {
      status: 'published',
      lastPublishedAt: '2026-03-15T22:00:00.000Z',
    },
  },
  cars: [
    {
      id: 'car-rolls-cloud',
      slug: '1964-rolls-royce-silver-cloud-iii',
      name: '1964 Rolls-Royce Silver Cloud III',
      brand: 'Rolls-Royce',
      model: 'Silver Cloud III',
      year: 1964,
      category: 'Vintage',
      style: 'Limousine',
      transmission: 'Automatic',
      seats: 4,
      location: 'Lisbon atelier',
      heroImage: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1600&q=80',
      accent: '#d4a457',
      summary: 'The signature wedding icon for timeless entrances and heirloom photographs.',
      story: 'A hand-finished British classic curated for ceremonies, editorial shoots, and discreet luxury arrivals. The Silver Cloud pairs beautifully with old-town venues, estates, and premium hotels.',
      tags: ['Ceremony-ready', 'White glove', 'Most requested'],
      featured: true,
      availabilityBlurb: 'Ideal for weddings, anniversaries, and heritage venue arrivals.',
      images: [
        { id: 'rolls-1', url: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1600&q=80', alt: 'Rolls-Royce Silver Cloud front profile' },
        { id: 'rolls-2', url: 'https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?auto=format&fit=crop&w=1600&q=80', alt: 'Classic luxury car interior detail' },
        { id: 'rolls-3', url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1600&q=80', alt: 'Vintage luxury car parked outside a venue' },
      ],
      features: [
        { id: 'rr-feature-1', label: 'Coach doors', detail: 'Elegant guest entry for ceremonial arrivals.' },
        { id: 'rr-feature-2', label: 'Curated ribbons', detail: 'Styled with event-ready detailing on request.' },
        { id: 'rr-feature-3', label: 'Ceremony pacing', detail: 'Optimized for photo timing and grand entrances.' },
      ],
      suitableEvents: ['wedding', 'anniversary', 'proposal', 'corporate'],
      includedExtraIds: ['extra-champagne', 'extra-florals'],
      pricing: {
        currency: 'EUR',
        basePrice: 720,
        minimumHours: 3,
        eventAdjustments: { wedding: 1.15, proposal: 1.05, photoshoot: 1.1, anniversary: 1.05, 'luxury-transfer': 1, corporate: 1.08, other: 1 },
        seasonalOverrides: [{ id: 'rr-june-premium', name: 'June wedding premium', startDate: '2026-06-01', endDate: '2026-06-30', type: 'multiplier', value: 1.12 }],
        quoteDisclosure: 'Final pricing varies with event logistics, itinerary, styling, and requested on-site time.',
      },
    },
    {
      id: 'car-ferrari-spider',
      slug: 'ferrari-488-spider',
      name: 'Ferrari 488 Spider',
      brand: 'Ferrari',
      model: '488 Spider',
      year: 2021,
      category: 'Exotic',
      style: 'Convertible',
      transmission: 'Automatic',
      seats: 2,
      location: 'Lisbon atelier',
      heroImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=80',
      accent: '#b84f3b',
      summary: 'A cinematic supercar for unforgettable proposals, editorials, and VIP arrivals.',
      story: 'Configured for statement making experiences, the 488 Spider delivers open air drama, modern craftsmanship, and unmistakable visual presence for high emotion events.',
      tags: ['Exotic icon', 'Photoshoot favorite', 'Grand entrance'],
      featured: true,
      availabilityBlurb: 'High demand in summer weekends and proposal evenings.',
      images: [
        { id: 'fer-1', url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=80', alt: 'Ferrari sports car side profile' },
        { id: 'fer-2', url: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=1600&q=80', alt: 'Ferrari cockpit detail' },
        { id: 'fer-3', url: 'https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=1600&q=80', alt: 'Luxury exotic car in motion' },
      ],
      features: [
        { id: 'fer-feature-1', label: 'Open top arrival', detail: 'Convertible styling for dramatic reveals.' },
        { id: 'fer-feature-2', label: 'Content ready finish', detail: 'Strong visual impact for commercial shoots.' },
        { id: 'fer-feature-3', label: 'Concierge delivery', detail: 'Handled by premium transfer specialists.' },
      ],
      suitableEvents: ['proposal', 'photoshoot', 'luxury-transfer', 'corporate'],
      includedExtraIds: ['extra-red-carpet', 'extra-content-support'],
      pricing: {
        currency: 'EUR',
        basePrice: 1120,
        minimumHours: 2,
        eventAdjustments: { wedding: 1.05, proposal: 1.14, photoshoot: 1.18, anniversary: 1.08, 'luxury-transfer': 1.1, corporate: 1.12, other: 1 },
        seasonalOverrides: [{ id: 'fer-august-explicit', name: 'Peak August demand', startDate: '2026-08-01', endDate: '2026-08-31', type: 'multiplier', value: 1.18 }],
        quoteDisclosure: 'Distance, staging time, convoy requirements, and content direction can change the final offer.',
      },
    },
    {
      id: 'car-mustang-fastback',
      slug: '1968-ford-mustang-fastback',
      name: '1968 Ford Mustang Fastback',
      brand: 'Ford',
      model: 'Mustang Fastback',
      year: 1968,
      category: 'Vintage',
      style: 'Statement',
      transmission: 'Manual',
      seats: 4,
      location: 'Sintra garage',
      heroImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1600&q=80',
      accent: '#8f6b46',
      summary: 'Muscle-era character for cinematic shoots, destination proposals, and modern celebrations.',
      story: 'This Fastback brings a more expressive editorial tone to the fleet. It works especially well for countryside sessions, hotel facades, and sunset driven moments.',
      tags: ['Editorial pick', 'Sunset sessions', 'Manual classic'],
      featured: true,
      availabilityBlurb: 'Popular for destination shoots and anniversary escapes.',
      images: [
        { id: 'mus-1', url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1600&q=80', alt: 'Classic Mustang parked outdoors' },
        { id: 'mus-2', url: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1600&q=80', alt: 'Classic car exterior detail' },
        { id: 'mus-3', url: 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&w=1600&q=80', alt: 'Classic steering wheel and interior' },
      ],
      features: [
        { id: 'mus-feature-1', label: 'Story led styling', detail: 'Perfect for high emotion visuals and reels.' },
        { id: 'mus-feature-2', label: 'Manual character', detail: 'Authentic driving feel for curated transfers.' },
        { id: 'mus-feature-3', label: 'Flexible routing', detail: 'Works beautifully across urban and coastal backdrops.' },
      ],
      suitableEvents: ['photoshoot', 'proposal', 'anniversary', 'other'],
      includedExtraIds: ['extra-content-support'],
      pricing: {
        currency: 'EUR',
        basePrice: 640,
        minimumHours: 3,
        eventAdjustments: { wedding: 1.02, proposal: 1.06, photoshoot: 1.14, anniversary: 1.08, 'luxury-transfer': 1, corporate: 1.05, other: 1 },
        seasonalOverrides: [],
        quoteDisclosure: 'Driver route, venue permissions, and creative direction may affect the tailored offer.',
      },
    },
    {
      id: 'car-bentley-s3',
      slug: '1963-bentley-s3',
      name: '1963 Bentley S3',
      brand: 'Bentley',
      model: 'S3',
      year: 1963,
      category: 'Vintage',
      style: 'Grand Tourer',
      transmission: 'Automatic',
      seats: 4,
      location: 'Cascais lounge',
      heroImage: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1600&q=80',
      accent: '#8da29b',
      summary: 'A discreet, refined classic for coastal weddings and executive hospitality.',
      story: 'Chosen by clients who want understated sophistication, the Bentley feels polished, calm, and quietly luxurious for bespoke ceremonies and guest transport.',
      tags: ['Executive favorite', 'Coastal venues', 'Refined finish'],
      featured: false,
      availabilityBlurb: 'Excellent for estate weddings, anniversaries, and executive hosting.',
      images: [
        { id: 'ben-1', url: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1600&q=80', alt: 'Classic Bentley in soft natural light' },
        { id: 'ben-2', url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=80', alt: 'Luxury exterior with elegant stance' },
      ],
      features: [
        { id: 'ben-feature-1', label: 'Estate friendly scale', detail: 'Confident presence without overpowering the scene.' },
        { id: 'ben-feature-2', label: 'Hospitality ready', detail: 'Ideal for clients, speakers, and VIP hosting.' },
      ],
      suitableEvents: ['wedding', 'corporate', 'anniversary', 'luxury-transfer'],
      includedExtraIds: ['extra-champagne'],
      pricing: {
        currency: 'EUR',
        basePrice: 680,
        minimumHours: 3,
        eventAdjustments: { wedding: 1.1, proposal: 1, photoshoot: 1.07, anniversary: 1.04, 'luxury-transfer': 1.06, corporate: 1.1, other: 1 },
        seasonalOverrides: [],
        quoteDisclosure: 'Offer will reflect route complexity, waiting time, and guest experience requirements.',
      },
    },
  ],
  extras: [
    { id: 'extra-champagne', name: 'Champagne welcome', description: 'Chilled luxury welcome service with glassware setup.', price: 120, pricingModel: 'fixed', category: 'service' },
    { id: 'extra-florals', name: 'Ceremony florals', description: 'Tailored floral ribbon and bonnet styling matched to palette.', price: 180, pricingModel: 'fixed', category: 'styling' },
    { id: 'extra-red-carpet', name: 'Red carpet arrival', description: 'Concierge unrolled arrival setup for high impact entrances.', price: 160, pricingModel: 'fixed', category: 'service' },
    { id: 'extra-content-support', name: 'Content support window', description: 'Additional positioning time for reels, editorials, and portraits.', price: 95, pricingModel: 'per-hour', category: 'service' },
  ],
  seasons: [
    { id: 'season-spring', name: 'Spring ceremonies', startDate: '2026-03-01', endDate: '2026-05-31', multiplier: 0.94, priority: 1, tone: '#8aa091' },
    { id: 'season-summer', name: 'Summer peak', startDate: '2026-06-01', endDate: '2026-09-15', multiplier: 1.18, priority: 2, tone: '#c48747' },
    { id: 'season-autumn', name: 'Autumn editorials', startDate: '2026-09-16', endDate: '2026-11-30', multiplier: 1.03, priority: 1, tone: '#8c6d57' },
    { id: 'season-winter', name: 'Winter elegance', startDate: '2026-12-01', endDate: '2027-02-28', multiplier: 0.92, priority: 1, tone: '#73879a' },
  ],
  customers: [
    { id: 'customer-sofia', name: 'Sofia Martins', email: 'sofia.martins@example.com', phone: '+351 912 300 410', city: 'Lisbon' },
    { id: 'customer-oliver', name: 'Oliver Reed', email: 'oliver.reed@example.com', phone: '+44 7550 000 145', city: 'London' },
  ],
  reservations: [
    {
      id: 'reservation-001',
      reference: 'RES-24015',
      customerId: 'customer-sofia',
      carId: 'car-rolls-cloud',
      eventType: 'wedding',
      startDate: '2026-06-18',
      endDate: '2026-06-18',
      startTime: '14:00',
      endTime: '19:00',
      pickupLocation: 'Palacio de Seteais, Sintra',
      destination: 'Penha Longa Resort',
      passengerCount: 2,
      extraIds: ['extra-florals'],
      notes: 'Arrival coordinated with ceremony planner.',
      preferredContactMethod: 'phone',
      status: 'confirmed',
      createdAt: '2026-01-28T09:00:00.000Z',
      estimatedPrice: 1290,
    },
    {
      id: 'reservation-002',
      reference: 'RES-24101',
      customerId: 'customer-oliver',
      carId: 'car-bentley-s3',
      eventType: 'corporate',
      startDate: '2026-04-22',
      endDate: '2026-04-22',
      startTime: '08:00',
      endTime: '12:00',
      pickupLocation: 'Four Seasons Ritz Lisbon',
      destination: 'Web Summit VIP venue',
      passengerCount: 3,
      extraIds: ['extra-champagne'],
      notes: 'Speaker hospitality and photography at hotel entrance.',
      preferredContactMethod: 'email',
      status: 'approved',
      createdAt: '2026-02-14T11:00:00.000Z',
      estimatedPrice: 980,
    },
    {
      id: 'reservation-003',
      reference: 'RES-24132',
      customerId: 'customer-sofia',
      carId: 'car-mustang-fastback',
      eventType: 'anniversary',
      startDate: '2026-05-09',
      endDate: '2026-05-09',
      startTime: '17:00',
      endTime: '20:00',
      pickupLocation: 'Cascais Marina',
      destination: 'Guincho viewpoint',
      passengerCount: 2,
      extraIds: ['extra-content-support'],
      notes: 'Sunset photo stop requested.',
      preferredContactMethod: 'whatsapp',
      status: 'pending',
      createdAt: '2026-03-02T18:30:00.000Z',
      estimatedPrice: 845,
    },
  ],
  quotes: [
    {
      id: 'quote-001',
      reference: 'QTE-18003',
      customerId: 'customer-sofia',
      carId: 'car-ferrari-spider',
      eventType: 'proposal',
      eventDate: '2026-07-11',
      startTime: '18:30',
      endTime: '21:30',
      pickupLocation: 'Belvedere rooftop, Lisbon',
      destination: 'Private dinner venue',
      passengerCount: 2,
      extraIds: ['extra-red-carpet'],
      notes: 'Need discreet coordination before reveal.',
      preferredContactMethod: 'whatsapp',
      status: 'quote-sent',
      createdAt: '2026-03-01T12:15:00.000Z',
      estimatedPrice: 1640,
    },
    {
      id: 'quote-002',
      reference: 'QTE-18011',
      customerId: 'customer-oliver',
      carId: 'car-rolls-cloud',
      eventType: 'photoshoot',
      eventDate: '2026-04-08',
      endDate: '2026-04-08',
      startTime: '09:00',
      endTime: '13:00',
      pickupLocation: 'LX Factory',
      destination: 'Palacio Nacional de Queluz',
      passengerCount: 4,
      extraIds: ['extra-content-support'],
      notes: 'Editorial shoot for boutique hotel collaboration.',
      preferredContactMethod: 'email',
      status: 'reviewing',
      createdAt: '2026-03-10T10:10:00.000Z',
      estimatedPrice: 1190,
    },
  ],
  blockedDates: [
    { id: 'block-001', carId: 'car-ferrari-spider', startDate: '2026-06-22', endDate: '2026-06-24', status: 'blocked', source: 'manual-block', label: 'Detailing and maintenance window' },
    { id: 'block-002', carId: 'car-bentley-s3', startDate: '2026-04-16', endDate: '2026-04-17', status: 'blocked', source: 'manual-block', label: 'Venue rehearsal hold' },
  ],
  testimonials: [
    { id: 'testimonial-1', name: 'Helena & Miguel', title: 'Wedding couple', quote: 'The entire experience felt like a luxury hospitality service, not just a car booking. The arrival timing, styling, and communication were flawless.' },
    { id: 'testimonial-2', name: 'Atelier Aurora', title: 'Creative production studio', quote: 'We booked the Mustang for a campaign shoot and the team handled logistics like a production partner. It elevated the whole story.' },
    { id: 'testimonial-3', name: 'Maison Vela', title: 'Concierge partner', quote: 'Chauffeur has become our go to fleet partner for VIP guests because the operation is calm, polished, and dependable.' },
  ],
  faqs: [
    { id: 'faq-1', question: 'Can I book a car only for photos?', answer: 'Yes. Photoshoots, proposals, brand campaigns, and anniversary sessions are all core use cases. We tailor the offer to route, duration, and positioning time.' },
    { id: 'faq-2', question: 'Is the listed price the final amount?', answer: 'The listed price is a premium starting point. Final pricing depends on the date, event type, timing, distance, waiting time, and requested extras.' },
    { id: 'faq-3', question: 'How far in advance should we book?', answer: 'For weddings and peak summer weekends, we recommend six to twelve weeks. Proposal and editorial sessions can often be arranged faster, subject to availability.' },
    { id: 'faq-4', question: 'Can the manager block dates manually?', answer: 'Yes. The operations area supports manual blocks for maintenance, rehearsals, travel windows, and venue specific holds.' },
  ],
  steps: [
    { id: 'step-1', title: 'Share the moment', description: 'Choose your event type, date, and any first preferences so the fleet can be filtered instantly.' },
    { id: 'step-2', title: 'Review available cars', description: 'Compare atmosphere, features, indicative pricing, and suitability before opening the full details page.' },
    { id: 'step-3', title: 'Request a tailored offer', description: 'Add itinerary, extras, and contact preferences. The summary makes every request transparent before you send it.' },
    { id: 'step-4', title: 'Confirm with concierge', description: 'The team finalizes logistics, approves the reservation, and keeps the experience calm from first inquiry to event day.' },
  ],
};
